apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: mealie-mcp-harbor-pull
  namespace: mealie-mcp
spec:
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-machine-identity
        secretNamespace: infisical-operator
      secretsScope:
        envSlug: prod
        projectSlug: homelab-bz-gt
        recursive: false
        secretsPath: /
  hostAPI: https://infisical.sirddail.net/api
  managedSecretReference:
    creationPolicy: Orphan
    secretName: mealie-mcp-harbor-pull
    secretNamespace: mealie-mcp
    secretType: kubernetes.io/dockerconfigjson
    template:
      data:
        .dockerconfigjson: '{"auths":{"{{ .HB_REGISTRY.Value }}":{"username":"{{ .HB_USERNAME.Value }}","password":"{{ .HB_PASSWORD.Value }}","auth":"{{ .HB_AUTH.Value }}"},"harbor-core.harbor.svc.cluster.local":{"username":"{{ .HB_USERNAME.Value }}","password":"{{ .HB_PASSWORD.Value }}","auth":"{{ .HB_AUTH.Value }}"}}}'
      includeAllSecrets: false
  resyncInterval: 60
