apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: mealie-mcp-infisical-secret
  namespace: mealie-mcp
spec:
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-machine-identity
        secretNamespace: infisical-operator
      secretsScope:
        envSlug: prod
        projectSlug: homelab-bz-gt
        recursive: false
        secretsPath: /
  hostAPI: https://infisical.sirddail.net/api
  managedSecretReference:
    creationPolicy: Owner
    secretName: mealie-mcp-secrets
    secretNamespace: mealie-mcp
    secretType: Opaque
    template:
      data:
        MEALIE_API_KEY: '{{ .MEALIE_API_KEY.Value }}'
      includeAllSecrets: false
  resyncInterval: 60
