apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - vpa.yaml
  - image-updater-rbac.yaml
  - harbor-pull-secret.yaml
