name: Validate Kustomize

on:
  pull_request:
    paths:
      - '**/*.yaml'

jobs:
  kustomize-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Validate kustomize build
        run: |
          kubectl kustomize overlays | kubectl apply --dry-run=client -f -
